import { ADMIN_MENU, CLIENT_MENU, STAFF_MENU, type ChipId } from "@/lib/chatbot/chip-labels";
import { generateWorkoutPlan } from "@/lib/chatbot/intents/workout-plan";
import type { IntentResult, SessionUser } from "@/lib/chatbot/types";
export type { ChipId } from "@/lib/chatbot/chip-labels";
export { CHIP_LABELS } from "@/lib/chatbot/chip-labels";
type ChipParams = { memberId?: string }; type ClassRow = { name: string; type: string; instructor: string; class_date: string; start_time: string; capacity: number; booked_count: number };
function staffOnly(session: SessionUser) { return session.role === "staff" || session.role === "admin" ? null : { reply: "That FitBot shortcut is available to staff only." }; } function clientOnly(session: SessionUser) { return session.role === "client" ? null : { reply: "That FitBot shortcut is available to members only." }; } function adminOnly(session: SessionUser) { return session.role === "admin" ? null : { reply: "That FitBot shortcut is available to admins only." }; } function dateString(date: Date) { return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`; } function formatDate(date: string) { const [year, month, day] = date.split("-").map(Number); return new Intl.DateTimeFormat("en-US", { weekday: "short", month: "short", day: "numeric" }).format(new Date(year, month - 1, day)); } function formatTime(time: string) { const [hours, minutes] = time.split(":").map(Number); return `${hours % 12 || 12}:${String(minutes).padStart(2, "0")} ${hours >= 12 ? "PM" : "AM"}`; } function scheduleCard(classes: ClassRow[]) { return { kind: "schedule" as const, classes: classes.map((classRow) => ({ title: classRow.name, type: classRow.type, instructor: classRow.instructor, date: classRow.class_date, time: classRow.start_time, capacity: classRow.capacity, bookedCount: classRow.booked_count })) }; }
export const chips: Record<ChipId, (session: SessionUser, params?: ChipParams) => Promise<IntentResult>> = {
  "recommend-class": async (session) => { const forbidden = clientOnly(session); if (forbidden) return forbidden; const { recommendClassIntent } = await import("@/lib/chatbot/intents/recommend-class"); return recommendClassIntent.handle("recommend a class", session); },
  "whats-next": async (session) => { const { nowAndNextIntent } = await import("@/lib/chatbot/intents/now-and-next"); return nowAndNextIntent.handle("what's happening now", session); },
  "studio-capacity": async (session) => { const forbidden = staffOnly(session); if (forbidden) return forbidden; const { getStudioCapacity } = await import("@/lib/chatbot/intents/studio-capacity"); return getStudioCapacity(); },
  "instructor-classes": async () => { const { getInstructorClasses } = await import("@/lib/chatbot/intents/instructor-classes"); return getInstructorClasses(""); },
  "roster-summary": async (session) => { const forbidden = staffOnly(session); if (forbidden) return forbidden; const { getRosterSummary } = await import("@/lib/chatbot/intents/roster-summary"); return getRosterSummary(); },
  // Staff/admin identity lives in profiles, not the members table (members
  // holds the 300 synthetic gym members + instructors, not real staff/admin
  // accounts like the 4 promoted @pursuit.org ones).
  "pending-time-off": async (session) => { const forbidden = adminOnly(session); if (forbidden) return forbidden; const [{ createSupabaseServerClient }, { listPendingTimeOffRequests }] = await Promise.all([import("@/lib/supabase/server"), import("@/lib/time-off/queries")]); try { const pending = await listPendingTimeOffRequests(await createSupabaseServerClient()); if (!pending.length) return { reply: "No pending time-off requests right now." }; return { reply: `Pending time-off requests:\n${pending.map((request) => `${request.full_name ?? "Staff member"} — ${formatDate(request.requested_date)}.`).join("\n")}`, card: { kind: "time-off", requests: pending.map((request) => ({ id: request.id, name: request.full_name ?? "Staff member", reason: request.reason, date: request.requested_date })) } }; } catch { return { reply: "I couldn’t retrieve pending time-off requests right now. Please try again shortly." }; } },
  "quick-workout": async () => ({ ...generateWorkoutPlan({ durationMinutes: 20, goal: "general", equipment: "bodyweight", level: "beginner" }), suggestedChips: ["plan-my-week", "build-consistency", "menu"] }),
  "plan-my-week": async () => ({ ...generateWorkoutPlan({ durationMinutes: 30, goal: "general", equipment: "bodyweight", level: "beginner", weekly: true }), suggestedChips: ["quick-workout", "build-consistency", "menu"] }),
  "build-consistency": async () => ({ reply: "Make the goal small enough to repeat: choose a specific weekly target, such as two classes or two 20-minute workouts. Put those sessions on your calendar before the week starts, and pair each with something you already do—like training right after your workday or after morning coffee. Track only whether you showed up; after two steady weeks, add a third session if it still feels sustainable.", suggestedChips: ["quick-workout", "plan-my-week", "menu"] }),
  "retention-outreach": async (session) => { const forbidden = staffOnly(session); if (forbidden) return forbidden; const [{ createSupabaseServerClient }, { getRetentionCandidates }] = await Promise.all([import("@/lib/supabase/server"), import("@/lib/chatbot/intents/retention-lookup")]); const supabase = await createSupabaseServerClient(); const { candidates, error } = await getRetentionCandidates(supabase); if (error) return { reply: "I couldn’t retrieve member lifecycle data right now. Please try again shortly." }; if (!candidates.length) return { reply: "There are no at-risk or lapsed members needing re-engagement right now." }; return { reply: `These members need re-engagement:\n${candidates.map((member) => member.full_name || member.email).join("\n")}\n\nYou can now say “draft outreach for {name}” for any one of them.`, card: { kind: "members", title: "Members needing re-engagement", members: candidates.map((member) => ({ name: member.full_name || member.email, email: member.email, status: member.lifecycle_status, reason: `Lifecycle status: ${member.lifecycle_status}` })) }, suggestedChips: ["member-lookup", "menu"] }; },
  "time-off-coverage": async (session) => { const forbidden = staffOnly(session); if (forbidden) return forbidden; const [{ createSupabaseServerClient }, { listMembersForStaff }] = await Promise.all([import("@/lib/supabase/server"), import("@/lib/members/queries")]); const supabase = await createSupabaseServerClient(); const today = new Date(); today.setHours(0, 0, 0, 0); const end = new Date(today); end.setDate(end.getDate() + 7); const [{ data: classes, error: classError }, { data: requests, error: requestError }, { data: members, error: memberError }] = await Promise.all([supabase.from("classes").select("name, instructor, class_date, start_time").gte("class_date", dateString(today)).lte("class_date", dateString(end)).order("class_date").order("start_time"), supabase.from("time_off_requests").select("user_id, requested_date, status").eq("status", "pending").gte("requested_date", dateString(today)).lte("requested_date", dateString(end)).order("requested_date"), listMembersForStaff(supabase)]); if (classError || requestError || memberError) return { reply: "I couldn’t retrieve this week’s coverage details right now. Please try again shortly." }; const instructorByUser = new Map((members ?? []).filter((member) => member.is_instructor && member.auth_user_id).map((member) => [member.auth_user_id as string, member.full_name || member.email])); const pending = (requests ?? []) as Array<{ user_id: string; requested_date: string; status: string }>; if (!pending.length) return { reply: "There are no pending time-off requests in the next 7 days, so there’s nothing to cover right now." }; const coverage = pending.map((request) => { const instructor = instructorByUser.get(request.user_id); const affected = instructor ? (classes ?? []).filter((classRow) => classRow.instructor.toLowerCase() === instructor.toLowerCase() && classRow.class_date === request.requested_date) : []; return `${formatDate(request.requested_date)} — ${instructor ?? "Staff member"}: ${affected.length ? affected.map((classRow) => `${classRow.name} at ${formatTime(classRow.start_time)}`).join(", ") : instructor ? "no scheduled classes" : "name not linked to an instructor profile"}.`; }); return { reply: `Pending time-off coverage for the next 7 days:\n${coverage.join("\n")}` }; },
  "member-lookup": async (session) => { const forbidden = staffOnly(session); return forbidden ?? { reply: "Tell me the member’s name or email and I’ll look them up." }; },
  "member-summary": async (session, params) => { const forbidden = staffOnly(session); if (forbidden) return forbidden; if (!params?.memberId) return { reply: "Choose a member first, then I can prepare their summary." }; const [{ createSupabaseServerClient }, { getMemberById }] = await Promise.all([import("@/lib/supabase/server"), import("@/lib/members/queries")]); const supabase = await createSupabaseServerClient(); const { data: member, error } = await getMemberById(supabase, params.memberId); if (error) return { reply: "I couldn’t retrieve that member right now. Please try again shortly." }; if (!member) return { reply: "I couldn’t find that member." }; const name = member.full_name || member.email; const reason = `Level: ${member.fitness_level ?? "not set"} · Goals: ${member.goals ?? "not set"} · Last visit: ${member.last_visit_date ?? "not recorded"}`; return { reply: `${name}\n${member.email}\nLifecycle: ${member.lifecycle_status}\nFitness level: ${member.fitness_level ?? "not set"}\nGoals: ${member.goals ?? "not set"}\nLast visit: ${member.last_visit_date ?? "not recorded"}`, card: { kind: "members", title: "Member summary", members: [{ name, email: member.email, status: member.lifecycle_status, reason }] } }; },
  "my-activity": async (session) => { const forbidden = clientOnly(session); if (forbidden) return forbidden; const [{ createSupabaseServerClient }, { getMemberActivitySummary }] = await Promise.all([import("@/lib/supabase/server"), import("@/lib/chatbot/intents/my-activity")]); return getMemberActivitySummary(await createSupabaseServerClient(), session.user.id); },
  "todays-schedule": async () => { const { createSupabaseServerClient } = await import("@/lib/supabase/server"); const { data, error } = await (await createSupabaseServerClient()).from("classes").select("name, type, instructor, class_date, start_time, capacity, booked_count").eq("class_date", dateString(new Date())).order("start_time"); if (error) return { reply: "I couldn’t retrieve today’s schedule right now. Please try again shortly." }; const classes = (data ?? []) as ClassRow[]; if (!classes.length) return { reply: "There are no classes on today’s schedule." }; return { reply: `Here’s today’s schedule:\n${classes.map((classRow) => `${classRow.name} (${classRow.type}) with ${classRow.instructor} — ${formatTime(classRow.start_time)}.`).join("\n")}`, card: scheduleCard(classes) }; },
  "my-appointments": async (session) => { const forbidden = clientOnly(session); if (forbidden) return forbidden; const { createSupabaseServerClient } = await import("@/lib/supabase/server"); const { data, error } = await (await createSupabaseServerClient()).from("bookings").select("created_at, classes!inner(name, type, instructor, class_date, start_time, capacity, booked_count)").eq("user_id", session.user.id).gte("classes.class_date", dateString(new Date())).order("created_at", { ascending: true }); if (error) return { reply: "I couldn’t retrieve your upcoming bookings right now. Please try again shortly." }; const classes = (data ?? []).map((booking) => booking.classes as unknown as ClassRow | null).filter((classRow): classRow is ClassRow => classRow !== null).sort((a, b) => `${a.class_date} ${a.start_time}`.localeCompare(`${b.class_date} ${b.start_time}`)); if (!classes.length) return { reply: "You don’t have any upcoming class bookings. Ask me what’s on the schedule to find a class." }; return { reply: `Here are your upcoming bookings:\n${classes.map((classRow) => `${classRow.name} (${classRow.type}) with ${classRow.instructor} — ${formatDate(classRow.class_date)}, ${formatTime(classRow.start_time)}.`).join("\n")}`, card: scheduleCard(classes) }; },
  "menu": async (session) => ({ reply: "Here’s what I can help with:", suggestedChips: session.role === "admin" ? ADMIN_MENU : session.role === "staff" ? STAFF_MENU : CLIENT_MENU }),
};
