"use client";

import { useRouter } from "next/navigation"; import { FormEvent, useEffect, useRef, useState } from "react"; import { IconClose, IconSparkle, IconUser, MomentumArc } from "@/app/components/icons"; import { ChatCard } from "@/app/components/chat-cards"; import { CHIP_LABELS, CHIP_ROLES, type ChipId } from "@/lib/chatbot/chip-labels"; import type { RichCard } from "@/lib/chatbot/types"; import { getLastSeenPromotion, setLastSeenPromotion } from "@/lib/promotions/seen-tracking";
type Role = "client" | "staff" | "admin";
type Message = { role: "assistant" | "user"; content: string; card?: RichCard; suggestedChips?: ChipId[] }; const greetingChips: ChipId[] = ["quick-workout", "plan-my-week", "menu"]; const greeting: Message = { role: "assistant", content: "Hey, I’m Fitbot. What do you want to move toward today?", suggestedChips: greetingChips };
const TYPING_MIN_VISIBLE_MS = 550;
async function runWithTypingFloor<T>(action: () => Promise<T>): Promise<T> { const startedAt = Date.now(); try { return await action(); } finally { const elapsed = Date.now() - startedAt; if (elapsed < TYPING_MIN_VISIBLE_MS) await new Promise((resolve) => setTimeout(resolve, TYPING_MIN_VISIBLE_MS - elapsed)); } }
export function ChatbotOverlay() {
  const router = useRouter();
  const [isOpen, setIsOpen] = useState(false); const [messages, setMessages] = useState<Message[]>([]); const [input, setInput] = useState(""); const [isSending, setIsSending] = useState(false); const [callerRole, setCallerRole] = useState<Role | null>(null); const inputRef = useRef<HTMLInputElement>(null); const messageListRef = useRef<HTMLDivElement>(null); const openerRef = useRef<HTMLElement | null>(null); const sendChipRef = useRef<((chipId: ChipId, params?: { memberId?: string }) => Promise<void>) | null>(null);
  // Server-computed suggestedChips are already the real security boundary (recomputed fresh
  // from the live session role on every request); this client-side CHIP_ROLES filter is a
  // cheap defense-in-depth pass so a stale/mismatched chip array can never render a button
  // for a role the current session doesn't hold.
  const suggestedChips = ([...messages].reverse().find((message) => message.role === "assistant")?.suggestedChips ?? greetingChips).filter((chipId) => !callerRole || CHIP_ROLES[chipId].includes(callerRole));
  useEffect(() => { let isMounted = true; async function loadMessages() { try { const response = await fetch("/api/chat"); if (!response.ok) throw new Error("Unable to load chat history"); const data = (await response.json()) as { messages?: Message[]; role?: Role; userId?: string }; if (isMounted) { const loadedMessages = (data.messages ?? []) as Array<Message & { created_at?: string; is_promotional?: boolean }>; setMessages(loadedMessages.length ? loadedMessages : [greeting]); if (data.role) setCallerRole(data.role); if (data.userId) { const lastSeen = getLastSeenPromotion(data.userId); const storedTime = lastSeen ? Date.parse(lastSeen) : Number.NEGATIVE_INFINITY; const lastSeenTime = Number.isFinite(storedTime) ? storedTime : Number.NEGATIVE_INFINITY; const newestPromotion = loadedMessages.filter((message) => message.is_promotional === true && message.created_at && Number.isFinite(Date.parse(message.created_at)) && Date.parse(message.created_at) > lastSeenTime).sort((a, b) => Date.parse(b.created_at!) - Date.parse(a.created_at!))[0]; if (newestPromotion?.created_at) { setLastSeenPromotion(data.userId, newestPromotion.created_at); setIsOpen(true); } } } } catch { if (isMounted) setMessages([greeting]); } } void loadMessages(); return () => { isMounted = false; }; }, []);
  useEffect(() => { if (isOpen) inputRef.current?.focus(); }, [isOpen]); useEffect(() => { messageListRef.current?.scrollTo({ top: messageListRef.current.scrollHeight }); }, [isOpen, messages, isSending]); useEffect(() => { function openFromLauncher(event: Event) { const detail = (event as CustomEvent<{ chipId?: ChipId; memberId?: string; preset?: string }>).detail; openerRef.current = document.activeElement instanceof HTMLElement ? document.activeElement : null; setIsOpen(true); if (detail?.chipId) void sendChipRef.current?.(detail.chipId, { memberId: detail.memberId }); else if (detail?.preset) setInput(detail.preset); } window.addEventListener("fitbot:open", openFromLauncher); return () => window.removeEventListener("fitbot:open", openFromLauncher); }, []);
  function openFromFloatingLauncher(event: React.MouseEvent<HTMLButtonElement>) { openerRef.current = event.currentTarget; setIsOpen(true); } function closeOverlay() { setIsOpen(false); window.setTimeout(() => openerRef.current?.focus(), 0); }
  async function sendMessage(event?: FormEvent<HTMLFormElement>, preset?: string) { event?.preventDefault(); const message = (preset ?? input).trim(); if (!message || isSending) return; setMessages((current) => [...current, { role: "user", content: message }]); setInput(""); setIsSending(true); try { await runWithTypingFloor(async () => { const response = await fetch("/api/chat", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ message }) }); if (!response.ok) throw new Error("Unable to send message"); const data = (await response.json()) as { reply?: string; card?: RichCard; suggestedChips?: ChipId[]; role?: Role }; if (data.role) setCallerRole(data.role); setMessages((current) => [...current, { role: "assistant", content: data.reply ?? "I’m here. Let’s take the next step together.", card: data.card, suggestedChips: data.suggestedChips ?? greetingChips }]); router.refresh(); }); } catch { setMessages((current) => [...current, { role: "assistant", content: "I hit a small snag. Try that again and we’ll keep moving.", suggestedChips: greetingChips }]); } finally { setIsSending(false); inputRef.current?.focus(); } }
  async function sendChip(chipId: ChipId, params?: { memberId?: string }) { if (isSending) return; setMessages((current) => [...current, { role: "user", content: CHIP_LABELS[chipId] }]); setInput(""); setIsSending(true); try { await runWithTypingFloor(async () => { const response = await fetch("/api/chat", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ chipId, params }) }); if (!response.ok) throw new Error("Unable to send chip"); const data = (await response.json()) as { reply?: string; card?: RichCard; suggestedChips?: ChipId[]; role?: Role }; if (data.role) setCallerRole(data.role); setMessages((current) => [...current, { role: "assistant", content: data.reply ?? "I’m here. Let’s take the next step together.", card: data.card, suggestedChips: data.suggestedChips ?? greetingChips }]); router.refresh(); }); } catch { setMessages((current) => [...current, { role: "assistant", content: "I hit a small snag. Try that again and we’ll keep moving.", suggestedChips: greetingChips }]); } finally { setIsSending(false); inputRef.current?.focus(); } }
  useEffect(() => { sendChipRef.current = sendChip; }); if (!isOpen) return <button className="chatbot-launcher" type="button" onClick={openFromFloatingLauncher} aria-label="Open Fitbot chat"><MomentumArc className="chatbot-launcher-arc" /><IconSparkle /><span>Fitbot</span></button>;
  return <section className="chatbot-overlay animate-scale-in" aria-label="Conversation with Fitbot"><header className="chatbot-overlay-header"><div><span className="message-avatar assistant-avatar"><MomentumArc /></span><span className="wordmark">Fitbot</span></div><button type="button" onClick={closeOverlay} aria-label="Close Fitbot chat"><IconClose /></button></header><div className="message-list chatbot-message-list" ref={messageListRef}>{messages.map((message, index) => <div className="message-stack" key={`${message.role}-${index}`}><div className={`message-row ${message.role}`}><div className={`message-avatar ${message.role === "assistant" ? "assistant-avatar" : "user-avatar"}`}>{message.role === "assistant" ? <MomentumArc /> : <IconUser />}</div><p className={message.card ? "sr-only" : undefined} aria-live={message.role === "assistant" ? "polite" : undefined}>{message.content}</p></div>{message.card ? <ChatCard card={message.card} onSelectOption={(message) => sendMessage(undefined, message)} /> : null}</div>)}{isSending && <div className="message-row assistant"><div className="message-avatar assistant-avatar"><MomentumArc className="animate-spin-arc" /></div><p className="typing"><i /><i /><i /></p></div>}</div><div className="chat-starters chatbot-starters">{suggestedChips.map((chipId) => <button key={chipId} type="button" onClick={() => void sendChip(chipId)}>{CHIP_LABELS[chipId]}<span>→</span></button>)}</div><form className="chat-form chatbot-form" onSubmit={sendMessage}><label className="sr-only" htmlFor="chatbot-message">Message Fitbot</label><input ref={inputRef} id="chatbot-message" value={input} onChange={(event) => setInput(event.target.value)} placeholder="Tell Fitbot what’s on your mind..." disabled={isSending} /><button className="chat-menu-button" type="button" onClick={() => void sendChip("menu")} disabled={isSending}>☰<span className="sr-only">What can I ask?</span></button><button aria-label="Send message" disabled={!input.trim() || isSending} type="submit">↑</button></form><p className="chat-disclaimer">Fitbot gives general fitness guidance, not medical advice.</p></section>;
}
