"use client";

import { useRouter } from "next/navigation"; import { FormEvent, useEffect, useRef, useState } from "react"; import { IconClose, IconSparkle, IconUser, MomentumArc } from "@/app/components/icons"; import { ChatCard } from "@/app/components/chat-cards"; import { CHIP_LABELS, CHIP_ROLES, type ChipId } from "@/lib/chatbot/chip-labels"; import type { RichCard } from "@/lib/chatbot/types"; import { getLastSeenPromotion, setLastSeenPromotion } from "@/lib/promotions/seen-tracking";
type Role = "client" | "staff" | "admin";
type Message = { role: "assistant" | "user"; content: string; card?: RichCard; suggestedChips?: ChipId[] }; const greetingChips: ChipId[] = ["quick-workout", "plan-my-week", "menu"]; const greeting: Message = { role: "assistant", content: "Hey, I’m FitBot. Ask me about classes, bookings, your schedule, or your goals — or tap a suggestion below.", suggestedChips: greetingChips };
const TYPING_MIN_VISIBLE_MS = 550;
async function runWithTypingFloor<T>(action: () => Promise<T>): Promise<T> { const startedAt = Date.now(); try { return await action(); } finally { const elapsed = Date.now() - startedAt; if (elapsed < TYPING_MIN_VISIBLE_MS) await new Promise((resolve) => setTimeout(resolve, TYPING_MIN_VISIBLE_MS - elapsed)); } }
export function ChatbotOverlay() {
  const router = useRouter();
  const [isOpen, setIsOpen] = useState(false); const [messages, setMessages] = useState<Message[]>([]); const [input, setInput] = useState(""); const [isSending, setIsSending] = useState(false); const [callerRole, setCallerRole] = useState<Role | null>(null); const inputRef = useRef<HTMLInputElement>(null); const messageListRef = useRef<HTMLDivElement>(null); const openerRef = useRef<HTMLElement | null>(null); const sendChipRef = useRef<((chipId: ChipId, params?: { memberId?: string }) => Promise<void>) | null>(null);
  // Server-computed suggestedChips are already the real security boundary (recomputed fresh
  // from the live session role on every request); this client-side CHIP_ROLES filter is a
  // cheap defense-in-depth pass so a stale/mismatched chip array can never render a button
  // for a role the current session doesn't hold.
  const suggestedChips = ([...messages].reverse().find((message) => message.role === "assistant")?.suggestedChips ?? greetingChips).filter((chipId) => !callerRole || CHIP_ROLES[chipId].includes(callerRole));
  // Booking is client-only; default to hiding the schedule card's "view full
  // schedule" link until the role is confirmed rather than briefly showing a
  // link a staff/admin caller can't use.
  const canBookClass = callerRole === "client";
  // The overlay is much narrower than the full /chat page, so a long chip
  // list (the full role menu can run to 10-11) wraps into several rows and
  // crowds out the actual conversation. Cap what's shown by default and let
  // the user expand. Tracking *which* chip set was expanded (rather than a
  // plain boolean reset via effect) means a new turn's different chip set
  // is derived back to collapsed automatically, no effect required.
  const CHIP_PREVIEW_COUNT = 6;
  const chipsKey = suggestedChips.join(",");
  const [expandedChipsKey, setExpandedChipsKey] = useState<string | null>(null);
  const chipsExpanded = expandedChipsKey === chipsKey;
  const visibleChips = chipsExpanded ? suggestedChips : suggestedChips.slice(0, CHIP_PREVIEW_COUNT);
  const hiddenChipCount = suggestedChips.length - visibleChips.length;
  const loadMessagesRef = useRef<() => Promise<void>>(async () => {});
  useEffect(() => { let isMounted = true; async function loadMessages() { try { const response = await fetch("/api/chat"); if (!response.ok) throw new Error("Unable to load chat history"); const data = (await response.json()) as { messages?: Message[]; role?: Role; userId?: string }; if (isMounted) { const loadedMessages = (data.messages ?? []) as Array<Message & { created_at?: string; is_promotional?: boolean }>; setMessages(loadedMessages.length ? loadedMessages : [greeting]); if (data.role) setCallerRole(data.role); if (data.userId) { const lastSeen = getLastSeenPromotion(data.userId); const storedTime = lastSeen ? Date.parse(lastSeen) : Number.NEGATIVE_INFINITY; const lastSeenTime = Number.isFinite(storedTime) ? storedTime : Number.NEGATIVE_INFINITY; const newestPromotion = loadedMessages.filter((message) => message.is_promotional === true && message.created_at && Number.isFinite(Date.parse(message.created_at)) && Date.parse(message.created_at) > lastSeenTime).sort((a, b) => Date.parse(b.created_at!) - Date.parse(a.created_at!))[0]; if (newestPromotion?.created_at) { setLastSeenPromotion(data.userId, newestPromotion.created_at); setIsOpen(true); } } } } catch { if (isMounted) setMessages([greeting]); } } loadMessagesRef.current = loadMessages; void loadMessages(); return () => { isMounted = false; }; }, []);
  useEffect(() => { if (isOpen) inputRef.current?.focus(); }, [isOpen]); useEffect(() => { messageListRef.current?.scrollTo({ top: messageListRef.current.scrollHeight }); }, [isOpen, messages, isSending]); useEffect(() => { function openFromLauncher(event: Event) { const detail = (event as CustomEvent<{ chipId?: ChipId; memberId?: string; preset?: string }>).detail; openerRef.current = document.activeElement instanceof HTMLElement ? document.activeElement : null; setIsOpen(true); void loadMessagesRef.current(); if (detail?.chipId) void sendChipRef.current?.(detail.chipId, { memberId: detail.memberId }); else if (detail?.preset) setInput(detail.preset); } window.addEventListener("fitbot:open", openFromLauncher); return () => window.removeEventListener("fitbot:open", openFromLauncher); }, []);
  // This component mounts once per page load and stays mounted across
  // client-side navigation (it lives in the root layout), but the full
  // /chat page is a separate mount with its own local state -- sending a
  // message there doesn't touch this component's state. Re-syncing from
  // /api/chat every time the launcher re-opens (not just on first mount)
  // is what keeps "close overlay, chat on /chat, reopen overlay" from
  // showing a stale, disconnected history.
  function openFromFloatingLauncher(event: React.MouseEvent<HTMLButtonElement>) { openerRef.current = event.currentTarget; setIsOpen(true); void loadMessagesRef.current(); } function closeOverlay() { setIsOpen(false); window.setTimeout(() => openerRef.current?.focus(), 0); }
  async function sendMessage(event?: FormEvent<HTMLFormElement>, preset?: string) { event?.preventDefault(); const message = (preset ?? input).trim(); if (!message || isSending) return; setMessages((current) => [...current, { role: "user", content: message }]); setInput(""); setIsSending(true); try { await runWithTypingFloor(async () => { const response = await fetch("/api/chat", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ message }) }); if (!response.ok) throw new Error("Unable to send message"); const data = (await response.json()) as { reply?: string; card?: RichCard; suggestedChips?: ChipId[]; role?: Role }; if (data.role) setCallerRole(data.role); setMessages((current) => [...current, { role: "assistant", content: data.reply ?? "I’m here. Let’s take the next step together.", card: data.card, suggestedChips: data.suggestedChips ?? greetingChips }]); router.refresh(); }); } catch { setMessages((current) => [...current, { role: "assistant", content: "I hit a small snag. Try that again and we’ll keep moving.", suggestedChips: greetingChips }]); } finally { setIsSending(false); inputRef.current?.focus(); } }
  async function sendChip(chipId: ChipId, params?: { memberId?: string }) { if (isSending) return; setMessages((current) => [...current, { role: "user", content: CHIP_LABELS[chipId] }]); setInput(""); setIsSending(true); try { await runWithTypingFloor(async () => { const response = await fetch("/api/chat", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ chipId, params }) }); if (!response.ok) throw new Error("Unable to send chip"); const data = (await response.json()) as { reply?: string; card?: RichCard; suggestedChips?: ChipId[]; role?: Role }; if (data.role) setCallerRole(data.role); setMessages((current) => [...current, { role: "assistant", content: data.reply ?? "I’m here. Let’s take the next step together.", card: data.card, suggestedChips: data.suggestedChips ?? greetingChips }]); router.refresh(); }); } catch { setMessages((current) => [...current, { role: "assistant", content: "I hit a small snag. Try that again and we’ll keep moving.", suggestedChips: greetingChips }]); } finally { setIsSending(false); inputRef.current?.focus(); } }
  useEffect(() => { sendChipRef.current = sendChip; }); if (!isOpen) return <button className="chatbot-launcher" type="button" onClick={openFromFloatingLauncher} aria-label="Open Fitbot chat"><MomentumArc className="chatbot-launcher-arc" /><IconSparkle /><span>Fitbot</span></button>;
  return <section className="chatbot-overlay animate-scale-in" aria-label="Conversation with Fitbot"><header className="chatbot-overlay-header"><div><img className="brand-icon chatbot-brand-icon" src="/gitfit-icon.gif" alt="" /><span className="wordmark">Fitbot</span></div><button type="button" onClick={closeOverlay} aria-label="Close Fitbot chat"><IconClose /></button></header><div className="message-list chatbot-message-list" ref={messageListRef}>{messages.map((message, index) => <div className="message-stack" key={`${message.role}-${index}`}><div className={`message-row ${message.role}`}>{message.role === "user" ? <div className="message-avatar user-avatar"><IconUser /></div> : null}<p className={message.card ? "sr-only" : undefined} aria-live={message.role === "assistant" ? "polite" : undefined}>{message.content}</p></div>{message.card ? <ChatCard canBookClass={canBookClass} card={message.card} onSelectOption={(message) => sendMessage(undefined, message)} /> : null}</div>)}{isSending && <div className="message-row assistant"><p className="typing"><i /><i /><i /></p></div>}</div><div className="chat-starters chatbot-starters">{visibleChips.map((chipId) => <button key={chipId} type="button" onClick={() => void sendChip(chipId)}>{CHIP_LABELS[chipId]}<span>→</span></button>)}{hiddenChipCount > 0 ? <button className="chatbot-starters-more" type="button" onClick={() => setExpandedChipsKey(chipsKey)}>Show {hiddenChipCount} more</button> : null}</div><form className="chat-form chatbot-form" onSubmit={sendMessage}><label className="sr-only" htmlFor="chatbot-message">Message Fitbot</label><input ref={inputRef} id="chatbot-message" value={input} onChange={(event) => setInput(event.target.value)} placeholder="Ask about classes, bookings, or your goals..." disabled={isSending} /><button className="chat-menu-button" type="button" onClick={() => void sendChip("menu")} disabled={isSending}>☰<span className="sr-only">What can I ask?</span></button><button aria-label="Send message" disabled={!input.trim() || isSending} type="submit">↑</button></form><p className="chat-disclaimer">Fitbot gives general fitness guidance, not medical advice.</p></section>;
}
