"use client";

import Link from "next/link"; import { FormEvent, useEffect, useRef, useState } from "react";
import { IconUser } from "@/app/components/icons"; import { ChatCard } from "@/app/components/chat-cards"; import { CHIP_LABELS, CHIP_ROLES, type ChipId } from "@/lib/chatbot/chip-labels"; import type { RichCard } from "@/lib/chatbot/types"; import { interpretChatResponse } from "@/lib/chatbot/interpret-chat-response";
type Role = "client" | "staff" | "admin";
type Message = { role: "assistant" | "user"; content: string; card?: RichCard; suggestedChips?: ChipId[] }; const greetingChips: ChipId[] = ["quick-workout", "plan-my-week", "menu"];
const greeting: Message = { role: "assistant", content: "Hey, I’m FitBot. Ask me about classes, bookings, your schedule, or your goals — or tap a suggestion below.", suggestedChips: greetingChips };
const TYPING_MIN_VISIBLE_MS = 550;
async function runWithTypingFloor<T>(action: () => Promise<T>): Promise<T> { const startedAt = Date.now(); try { return await action(); } finally { const elapsed = Date.now() - startedAt; if (elapsed < TYPING_MIN_VISIBLE_MS) await new Promise((resolve) => setTimeout(resolve, TYPING_MIN_VISIBLE_MS - elapsed)); } }
export function ChatExperience() {
  const [messages, setMessages] = useState<Message[]>([greeting]); const [input, setInput] = useState(""); const [isSending, setIsSending] = useState(false); const [callerRole, setCallerRole] = useState<Role | null>(null); const inputRef = useRef<HTMLInputElement>(null);
  // The floating launcher (ChatbotOverlay) loads this same persisted history
  // on mount -- this page didn't, so opening full chat looked like it erased
  // whatever conversation was already going. Same /api/chat GET, same
  // fallback-to-greeting-if-empty behavior, so both surfaces show one
  // continuous conversation instead of two disconnected ones.
  useEffect(() => { let isMounted = true; async function loadHistory() { try { const response = await fetch("/api/chat"); if (!response.ok) throw new Error("Unable to load chat history"); const data = (await response.json()) as { messages?: Message[]; role?: Role }; if (!isMounted) return; setMessages(data.messages?.length ? data.messages : [greeting]); if (data.role) setCallerRole(data.role); } catch { if (isMounted) setMessages([greeting]); } } void loadHistory(); return () => { isMounted = false; }; }, []);
  // Server-computed suggestedChips are already the real security boundary (recomputed fresh
  // from the live session role on every request); this client-side CHIP_ROLES filter is a
  // cheap defense-in-depth pass so a stale/mismatched chip array can never render a button
  // for a role the current session doesn't hold.
  const suggestedChips = ([...messages].reverse().find((message) => message.role === "assistant")?.suggestedChips ?? greetingChips).filter((chipId) => !callerRole || CHIP_ROLES[chipId].includes(callerRole));
  async function sendMessage(event?: FormEvent, preset?: string) { event?.preventDefault(); const message = (preset ?? input).trim(); if (!message || isSending) return; setMessages((current) => [...current, { role: "user", content: message }]); setInput(""); setIsSending(true); try { await runWithTypingFloor(async () => { const response = await fetch("/api/chat", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ message }) }); const data = await response.json(); const outcome = interpretChatResponse({ ok: response.ok, status: response.status, data }); if (outcome.kind === "reply") { if (outcome.role) setCallerRole(outcome.role); setMessages((current) => [...current, { role: "assistant", content: outcome.content, card: outcome.card, suggestedChips: outcome.suggestedChips ?? greetingChips }]); } else { setMessages((current) => [...current, { role: "assistant", content: outcome.content, suggestedChips: outcome.suggestedChips }]); } }); } catch { setMessages((current) => [...current, { role: "assistant", content: "I hit a small snag. Try that again and we’ll keep moving.", suggestedChips: greetingChips }]); } finally { setIsSending(false); inputRef.current?.focus(); } }
  async function sendChip(chipId: ChipId) { if (isSending) return; setMessages((current) => [...current, { role: "user", content: CHIP_LABELS[chipId] }]); setIsSending(true); try { await runWithTypingFloor(async () => { const response = await fetch("/api/chat", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ chipId }) }); if (!response.ok) throw new Error("Unable to send chip"); const data = await response.json(); if (data.role) setCallerRole(data.role); setMessages((current) => [...current, { role: "assistant", content: data.reply ?? "I’m here. Let’s take the next step together.", card: data.card, suggestedChips: data.suggestedChips ?? greetingChips }]); }); } catch { setMessages((current) => [...current, { role: "assistant", content: "I hit a small snag. Try that again and we’ll keep moving.", suggestedChips: greetingChips }]); } finally { setIsSending(false); inputRef.current?.focus(); } }
  return <main className="chat-shell"><header className="chat-header"><Link className="brand" href="/" aria-label="GitFit home"><img className="brand-icon" src="/gitfit-icon.gif" alt="" /><span className="wordmark">GitFit</span></Link><div className="bot-status"><span /><b className="bot-status-name">Fitbot</b><small>online</small></div><Link className="back-link" href="/">Exit chat <span aria-hidden="true">↗</span></Link><Link className="text-link" href="/appointments">Book a class</Link></header><section className="chat-layout"><aside className="chat-aside"><p className="eyebrow"><span /> Your training space</p><h1>One message can start a real change.</h1><p>FitBot is a guided assistant, not open-ended chat — it’s built to help with classes, bookings, your schedule, and your goals.</p><div className="aside-note"><b>✦</b><span>Try a suggestion below, or ask about a class, a booking, or your goals.</span></div></aside><section className="chat-panel" aria-label="Conversation with Fitbot"><div className="message-list">{messages.map((message, index) => <div className="message-stack" key={`${message.role}-${index}`}><div className={`message-row ${message.role}`}>{message.role === "user" ? <div className="message-avatar user-avatar"><IconUser /></div> : null}<p className={message.card ? "sr-only" : undefined} aria-live={message.role === "assistant" ? "polite" : undefined}>{message.content}</p></div>{message.card ? <ChatCard card={message.card} onSelectOption={(message) => sendMessage(undefined, message)} /> : null}</div>)}{isSending && <div className="message-row assistant"><p className="typing"><i /><i /><i /></p></div>}</div><div className="chat-starters">{suggestedChips.map((chipId) => <button key={chipId} type="button" onClick={() => void sendChip(chipId)}>{CHIP_LABELS[chipId]}<span>→</span></button>)}</div><form className="chat-form" onSubmit={(event) => sendMessage(event)}><label className="sr-only" htmlFor="message">Message Fitbot</label><input ref={inputRef} id="message" value={input} onChange={(event) => setInput(event.target.value)} placeholder="Ask about classes, bookings, or your goals..." disabled={isSending} /><button className="chat-menu-button" type="button" onClick={() => void sendChip("menu")} disabled={isSending}>☰<span className="sr-only">What can I ask?</span></button><button aria-label="Send message" disabled={!input.trim() || isSending} type="submit">↑</button></form><p className="chat-disclaimer">Fitbot gives general fitness guidance, not medical advice.</p></section></section></main>;
}
