"use client";

import Link from "next/link"; import { FormEvent, useRef, useState } from "react";
import { IconUser, MomentumArc } from "@/app/components/icons"; import { ChatCard } from "@/app/components/chat-cards"; import { CHIP_LABELS, CHIP_ROLES, type ChipId } from "@/lib/chatbot/chip-labels"; import type { RichCard } from "@/lib/chatbot/types";
type Role = "client" | "staff" | "admin";
type Message = { role: "assistant" | "user"; content: string; card?: RichCard; suggestedChips?: ChipId[] }; const greetingChips: ChipId[] = ["quick-workout", "plan-my-week", "menu"];
export function ChatExperience() {
  const [messages, setMessages] = useState<Message[]>([{ role: "assistant", content: "Hey, I’m Fitbot. What do you want to move toward today?", suggestedChips: greetingChips }]); const [input, setInput] = useState(""); const [isSending, setIsSending] = useState(false); const [callerRole, setCallerRole] = useState<Role | null>(null); const inputRef = useRef<HTMLInputElement>(null);
  // Server-computed suggestedChips are already the real security boundary (recomputed fresh
  // from the live session role on every request); this client-side CHIP_ROLES filter is a
  // cheap defense-in-depth pass so a stale/mismatched chip array can never render a button
  // for a role the current session doesn't hold.
  const suggestedChips = ([...messages].reverse().find((message) => message.role === "assistant")?.suggestedChips ?? greetingChips).filter((chipId) => !callerRole || CHIP_ROLES[chipId].includes(callerRole));
  async function sendMessage(event?: FormEvent, preset?: string) { event?.preventDefault(); const message = (preset ?? input).trim(); if (!message || isSending) return; setMessages((current) => [...current, { role: "user", content: message }]); setInput(""); setIsSending(true); try { const response = await fetch("/api/chat", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ message }) }); const data = await response.json(); if (data.role) setCallerRole(data.role); setMessages((current) => [...current, { role: "assistant", content: data.reply ?? "I’m here. Let’s take the next step together.", card: data.card, suggestedChips: data.suggestedChips ?? greetingChips }]); } catch { setMessages((current) => [...current, { role: "assistant", content: "I hit a small snag. Try that again and we’ll keep moving.", suggestedChips: greetingChips }]); } finally { setIsSending(false); inputRef.current?.focus(); } }
  async function sendChip(chipId: ChipId) { if (isSending) return; setMessages((current) => [...current, { role: "user", content: CHIP_LABELS[chipId] }]); setIsSending(true); try { const response = await fetch("/api/chat", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ chipId }) }); if (!response.ok) throw new Error("Unable to send chip"); const data = await response.json(); if (data.role) setCallerRole(data.role); setMessages((current) => [...current, { role: "assistant", content: data.reply ?? "I’m here. Let’s take the next step together.", card: data.card, suggestedChips: data.suggestedChips ?? greetingChips }]); } catch { setMessages((current) => [...current, { role: "assistant", content: "I hit a small snag. Try that again and we’ll keep moving.", suggestedChips: greetingChips }]); } finally { setIsSending(false); inputRef.current?.focus(); } }
  return <main className="chat-shell"><header className="chat-header"><Link className="brand" href="/" aria-label="GitFit home"><span className="wordmark">GitFit</span></Link><div className="bot-status"><span /><b className="bot-status-name">Fitbot</b><small>online</small></div><Link className="back-link" href="/">Exit chat <span aria-hidden="true">↗</span></Link><Link className="text-link" href="/appointments">Book a class</Link></header><section className="chat-layout"><aside className="chat-aside"><p className="eyebrow"><span /> Your training space</p><h1>One message can start a real change.</h1><p>Fitbot is your first stop for turning a goal into a game plan.</p><div className="aside-note"><b>✦</b><span>Try a goal, a question, or just tell me how your week is going.</span></div></aside><section className="chat-panel" aria-label="Conversation with Fitbot"><div className="message-list">{messages.map((message, index) => <div className="message-stack" key={`${message.role}-${index}`}><div className={`message-row ${message.role}`}><div className={`message-avatar ${message.role === "assistant" ? "assistant-avatar" : "user-avatar"}`}>{message.role === "assistant" ? <MomentumArc /> : <IconUser />}</div><p className={message.card ? "sr-only" : undefined} aria-live={message.role === "assistant" ? "polite" : undefined}>{message.content}</p></div>{message.card ? <ChatCard card={message.card} onSelectOption={(message) => sendMessage(undefined, message)} /> : null}</div>)}{isSending && <div className="message-row assistant"><div className="message-avatar assistant-avatar"><MomentumArc /></div><p className="typing"><i /><i /><i /></p></div>}</div><div className="chat-starters">{suggestedChips.map((chipId) => <button key={chipId} type="button" onClick={() => void sendChip(chipId)}>{CHIP_LABELS[chipId]}<span>→</span></button>)}</div><form className="chat-form" onSubmit={(event) => sendMessage(event)}><label className="sr-only" htmlFor="message">Message Fitbot</label><input ref={inputRef} id="message" value={input} onChange={(event) => setInput(event.target.value)} placeholder="Tell Fitbot what’s on your mind..." disabled={isSending} /><button className="chat-menu-button" type="button" onClick={() => void sendChip("menu")} disabled={isSending}>☰<span className="sr-only">What can I ask?</span></button><button aria-label="Send message" disabled={!input.trim() || isSending} type="submit">↑</button></form><p className="chat-disclaimer">Fitbot gives general fitness guidance, not medical advice.</p></section></section></main>;
}
