"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";

type ClassSession = { id: string; name: string; type: string; instructor: string; class_date: string; start_time: string; duration_minutes: number; capacity: number; booked_count: number; isBookedByCurrentUser: boolean };
type ApiError = { error?: { message?: string } };

function formatDay(date: string) { const [year, month, day] = date.split("-").map(Number); return new Intl.DateTimeFormat("en-US", { weekday: "short", month: "short", day: "numeric" }).format(new Date(year, month - 1, day)); }
function formatTime(time: string) { const [hours, minutes] = time.split(":").map(Number); return `${hours % 12 || 12}:${String(minutes).padStart(2, "0")} ${hours >= 12 ? "PM" : "AM"}`; }

export function AppointmentsExperience() {
  const [classes, setClasses] = useState<ClassSession[]>([]); const [activeDate, setActiveDate] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [pendingId, setPendingId] = useState<string | null>(null);
  useEffect(() => { void (async () => { try { const response = await fetch("/api/appointments/classes"); const payload = (await response.json()) as { classes?: ClassSession[] } & ApiError; if (!response.ok) throw new Error(payload.error?.message ?? "Unable to load classes."); const loaded = payload.classes ?? []; setClasses(loaded); setActiveDate(loaded[0]?.class_date ?? ""); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to load classes."); } finally { setLoading(false); } })(); }, []);
  const dates = useMemo(() => [...new Set(classes.map((classRow) => classRow.class_date))], [classes]); const visible = classes.filter((classRow) => classRow.class_date === activeDate);
  async function updateBooking(classRow: ClassSession) { const action = classRow.isBookedByCurrentUser ? "cancel" : "reserve"; setPendingId(classRow.id); setError(""); try { const response = await fetch(`/api/appointments/${action}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ classId: classRow.id }) }); const payload = (await response.json()) as ApiError; if (!response.ok) throw new Error(payload.error?.message ?? "Unable to update booking."); setClasses((current) => current.map((item) => item.id === classRow.id ? { ...item, isBookedByCurrentUser: !item.isBookedByCurrentUser, booked_count: item.booked_count + (item.isBookedByCurrentUser ? -1 : 1) } : item)); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to update booking."); } finally { setPendingId(null); } }
  return <main className="appointments-shell"><header className="appointments-header"><Link className="brand" href="/"><span className="wordmark">GitFit</span></Link></header><section className="appointments-content"><div className="appointments-heading"><div><p className="eyebrow"><span />Class schedule</p><h1>Book a class</h1><p>Reserve your spot in the next session that moves you.</p></div></div>{loading ? <p className="appointments-loading">Loading classes…</p> : error && classes.length === 0 ? <p className="appointments-error">{error}</p> : <><div className="day-tabs" aria-label="Class dates">{dates.map((date) => <button className={`day-tab ${date === activeDate ? "active" : ""}`} key={date} onClick={() => setActiveDate(date)} type="button"><span>{formatDay(date)}</span></button>)}</div>{error ? <p className="appointments-error">{error}</p> : null}<div className="schedule-heading"><h2>{activeDate ? formatDay(activeDate) : "Classes"}</h2><p>{visible.length} classes</p></div><div className="class-grid">{visible.map((classRow) => { const spots = classRow.capacity - classRow.booked_count; const isPending = pendingId === classRow.id; return <article className="class-card" key={classRow.id}><div className="class-card-top"><span className={`class-type ${classRow.type.toLowerCase()}`}><i />{classRow.type}</span><span className={`spots ${spots === 0 ? "full" : ""}`}>{spots === 0 ? "Full" : `${spots} spots left`}</span></div><h3>{classRow.name}</h3><p className="class-instructor">with {classRow.instructor}</p><div className="class-details"><span>{formatTime(classRow.start_time)}</span><span>{classRow.duration_minutes} min</span></div><div className="class-action">{classRow.isBookedByCurrentUser ? <p className="reserved">You’re booked</p> : spots === 0 ? <p className="full-action">No spots available</p> : <span />}{classRow.isBookedByCurrentUser ? <button className="cancel-button" disabled={isPending} onClick={() => void updateBooking(classRow)} type="button">{isPending ? "Cancelling…" : "Cancel"}</button> : <button className="reserve-button" disabled={isPending || spots === 0} onClick={() => void updateBooking(classRow)} type="button">{isPending ? "Reserving…" : "Reserve"}</button>}</div></article>; })}</div></>}</section></main>;
}
