"use client";

import { useEffect, useMemo, useState } from "react";
import { IconCalendarX } from "@/app/components/icons";
import { InstructorAvatar } from "@/app/components/instructor-avatar";

type ClassSession = { id: string; name: string; type: string; instructor: string; class_date: string; start_time: string; duration_minutes: number; capacity: number; booked_count: number; isBookedByCurrentUser: boolean };
type ApiError = { error?: { message?: string } };
const formatDay = (date: string) => { const [year, month, day] = date.split("-").map(Number); return new Intl.DateTimeFormat("en-US", { weekday: "short", month: "short", day: "numeric" }).format(new Date(year, month - 1, day)); };
const formatTime = (time: string) => { const [hours, minutes] = time.split(":").map(Number); return `${hours % 12 || 12}:${String(minutes).padStart(2, "0")} ${hours >= 12 ? "PM" : "AM"}`; };
const typeBadgeVariant = (type: string) => ({ yoga: "badge-success", cycling: "badge-brand", hiit: "badge-warning" }[type.toLowerCase()] ?? "badge-neutral");
const typeRuleVariant = (type: string) => ({ yoga: "class-type-yoga", cycling: "class-type-cycling", hiit: "class-type-hiit" }[type.toLowerCase()] ?? "class-type-default");

function ScheduleEmptyState({ heading, message }: { heading: string; message: string }) { return <div className="empty-state appointments-empty-state"><IconCalendarX className="empty-state-icon" /><h3>{heading}</h3><p>{message}</p></div>; }
function ClassCardSkeleton() { return <article aria-hidden="true" className="class-card class-card-skeleton surface-card"><div className="class-card-top"><span className="skeleton skeleton-badge" /><span className="skeleton skeleton-spots" /></div><div className="skeleton-instructor-unit"><span className="skeleton skeleton-instructor-avatar" /><span className="skeleton skeleton-instructor" /></div><span className="skeleton skeleton-title" /><div className="class-details"><span className="skeleton skeleton-detail" /><span className="skeleton skeleton-detail short" /></div><div className="class-action"><span className="skeleton skeleton-reserved" /><span className="skeleton skeleton-button" /></div></article>; }

export function AppointmentsExperience() {
  const [classes, setClasses] = useState<ClassSession[]>([]); const [activeDate, setActiveDate] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [pendingId, setPendingId] = useState<string | null>(null);
  useEffect(() => { void (async () => { try { const response = await fetch("/api/appointments/classes"); const payload = (await response.json()) as { classes?: ClassSession[] } & ApiError; if (!response.ok) throw new Error(payload.error?.message ?? "Unable to load classes."); const loaded = payload.classes ?? []; setClasses(loaded); setActiveDate(loaded[0]?.class_date ?? ""); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to load classes."); } finally { setLoading(false); } })(); }, []);
  const dates = useMemo(() => [...new Set(classes.map((classRow) => classRow.class_date))], [classes]); const visible = classes.filter((classRow) => classRow.class_date === activeDate);
  async function updateBooking(classRow: ClassSession) { const action = classRow.isBookedByCurrentUser ? "cancel" : "reserve"; setPendingId(classRow.id); setError(""); try { const response = await fetch(`/api/appointments/${action}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ classId: classRow.id }) }); const payload = (await response.json()) as ApiError; if (!response.ok) throw new Error(payload.error?.message ?? "Unable to update booking."); setClasses((current) => current.map((item) => item.id === classRow.id ? { ...item, isBookedByCurrentUser: !item.isBookedByCurrentUser, booked_count: item.booked_count + (item.isBookedByCurrentUser ? -1 : 1) } : item)); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to update booking."); } finally { setPendingId(null); } }
  const content = loading ? <div aria-label="Loading classes" className="class-grid class-grid-loading">{Array.from({ length: 3 }, (_, index) => <ClassCardSkeleton key={index} />)}</div> : error && classes.length === 0 ? <ScheduleEmptyState heading="We could not load the schedule" message={error} /> : <><div className="day-tabs" aria-label="Class dates">{dates.map((date) => <button aria-pressed={date === activeDate} className={`day-tab ${date === activeDate ? "active" : ""}`} key={date} onClick={() => setActiveDate(date)} type="button"><span>{formatDay(date)}</span></button>)}</div>{error ? <p className="appointments-error">{error}</p> : null}<div className="schedule-heading"><h2>{activeDate ? formatDay(activeDate) : "Classes"}</h2><p>{visible.length} classes</p></div>{visible.length === 0 ? <ScheduleEmptyState heading="No classes scheduled" message="Try another day when the next sessions are available." /> : <div className="class-grid">{visible.map((classRow, index) => { const spots = classRow.capacity - classRow.booked_count; const isPending = pendingId === classRow.id; return <article className={`class-card ${typeRuleVariant(classRow.type)} surface-card surface-card-interactive animate-fade-up`} key={classRow.id} style={{ animationDelay: `${Math.min(index, 5) * 55}ms` }}><div className="class-card-top"><span className={`class-type badge ${typeBadgeVariant(classRow.type)}`}>{classRow.type}</span><span className={`spots badge ${spots === 0 ? "badge-danger" : "badge-success"}`}>{spots === 0 ? "Full" : `${spots} spots left`}</span></div><div className="class-instructor-unit"><InstructorAvatar name={classRow.instructor} size={40} loading={index < 3 ? "eager" : "lazy"} /><span>{classRow.instructor}</span></div><h3>{classRow.name}</h3><div className="class-details"><span>{formatTime(classRow.start_time)}</span><span>{classRow.duration_minutes} min</span></div><div className="class-action">{classRow.isBookedByCurrentUser ? <p className="reserved badge badge-success booking-confirmed">You are booked</p> : spots === 0 ? <p className="full-action">No spots available</p> : <span />}{classRow.isBookedByCurrentUser ? <button className="cancel-button btn btn-outline btn-sm" disabled={isPending} onClick={() => void updateBooking(classRow)} type="button">{isPending ? "Cancelling..." : "Cancel"}</button> : <button className="reserve-button btn btn-primary btn-sm" disabled={isPending || spots === 0} onClick={() => void updateBooking(classRow)} type="button">{isPending ? "Reserving..." : "Reserve"}</button>}</div></article>; })}</div>}</>;
  return <section className="appointments-content"><div className="appointments-heading"><div><p className="eyebrow"><span />Class schedule</p><h1>Book a class</h1><p>Reserve your spot in the next session that moves you.</p></div></div>{content}</section>;
}
