import Link from "next/link";
import type { ReactNode } from "react";

import { signOut } from "@/app/actions/auth";
import { IconCalendar, IconSparkle } from "@/app/components/icons";
import MomentumRing from "@/app/components/momentum-ring";
import { ScheduleRow } from "@/app/components/schedule-row";
import { RecommendedClasses } from "@/app/dashboard/recommended-classes";
import type { StudioClass } from "@/lib/classes/queries";
import type { EncouragingMessageCategory } from "@/lib/dashboard/encouraging-messages";
import type { ClassRow } from "@/lib/members/queries";

type Promotion = { id: string; subject: string; body: string; sent_at: string | null };
const WEEKLY_BOOKING_TARGET = 4;
const formatDate = (date: string) => new Intl.DateTimeFormat("en-US", { weekday: "short", month: "short", day: "numeric" }).format(new Date(`${date}T00:00:00`));
const formatTime = (time: string) => { const [hours, minutes] = time.split(":").map(Number); return `${hours % 12 || 12}:${String(minutes).padStart(2, "0")} ${hours >= 12 ? "PM" : "AM"}`; };
const formatPromotionDate = (sentAt: string | null) => { if (!sentAt) return "Recently"; const date = new Date(sentAt); if (Number.isNaN(date.getTime())) return "Recently"; return new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", year: date.getFullYear() === new Date().getFullYear() ? undefined : "numeric" }).format(date); };
const previewPromotion = (body: string) => body.length > 150 ? `${body.slice(0, 147).trimEnd()}...` : body;
const typeBadgeVariant = (type: string) => ({ yoga: "badge-success", cycling: "badge-brand", hiit: "badge-warning", pilates: "badge-magenta", boxing: "badge-danger", strength: "badge-graphite" }[type.toLowerCase()] ?? "badge-neutral");
const typeRuleVariant = (type: string) => ({ yoga: "class-type-yoga", cycling: "class-type-cycling", hiit: "class-type-hiit", pilates: "class-type-pilates", boxing: "class-type-boxing", strength: "class-type-strength" }[type.toLowerCase()] ?? "class-type-default");

function SessionList({ classes, emptyTitle, emptyCopy }: { classes: ClassRow[]; emptyTitle: string; emptyCopy: ReactNode }) {
  return classes.length ? <ul className="staff-class-list">{classes.map((classRow) => <ScheduleRow key={`${classRow.class_date}-${classRow.start_time}-${classRow.name}`} name={classRow.name} meta={<span className="client-session-meta"><span>{classRow.instructor}</span><span className={`badge ${typeBadgeVariant(classRow.type)}`}>{classRow.type}</span></span>} actions={<time dateTime={classRow.class_date}>{formatDate(classRow.class_date)} · {formatTime(classRow.start_time)}</time>} className={typeRuleVariant(classRow.type)} />)}</ul> : <div className="empty-state client-dashboard-empty"><h3>{emptyTitle}</h3><p>{emptyCopy}</p></div>;
}

export function ClientDashboard({ bookedThisWeek, bookingHistory, currentWeekBooked, encouragingMessage, encouragingMessageCategory, memberFirstName, memberGoals, membershipTier, promotions, recommendedClasses, recommendationReason, streakWeeks, upcomingBookings, userEmail }: { bookedThisWeek: number; bookingHistory: ClassRow[]; currentWeekBooked: boolean; encouragingMessage: string; encouragingMessageCategory: EncouragingMessageCategory; memberFirstName: string | null; memberGoals: string | null; membershipTier: string | null; promotions: Promotion[] | null; recommendedClasses: StudioClass[]; recommendationReason: string | null; streakWeeks: number; upcomingBookings: ClassRow[]; userEmail?: string }) {
  const tierLabel = membershipTier ? membershipTier.charAt(0).toUpperCase() + membershipTier.slice(1) : "Member";
  const weeklyProgressPct = Math.min(100, Math.round((bookedThisWeek / WEEKLY_BOOKING_TARGET) * 100));
  const goals = memberGoals?.split(";").map((goal) => goal.trim()).filter(Boolean) ?? [];
  return <main className="account-content client-dashboard-content">
    <header className="account-intro animate-fade-up"><p className="eyebrow"><span /> Your home base</p><h1>{memberFirstName ? `Ready when you are, ${memberFirstName}.` : "Ready when you are."}</h1><p>Keep your routine moving, see what&apos;s next, or ask FitBot for a little guidance.</p></header>
    <section className="surface-card dashboard-card client-momentum-card animate-fade-up" style={{ animationDelay: ".08s" }}><div className="dashboard-card-top"><div><h2>Your momentum</h2><p className="dashboard-email">Signed in as {userEmail}</p></div><span className="badge badge-neutral">{tierLabel}</span></div><div className="dashboard-momentum client-streak"><MomentumRing target={8} value={streakWeeks} /><div><h3>{streakWeeks === 1 ? "1 completed week in your streak" : `${streakWeeks} completed weeks in your streak`}</h3><p className={`client-streak-message client-streak-tone-${encouragingMessageCategory}`}>{encouragingMessage}</p><span className={`client-week-status ${currentWeekBooked ? "is-booked" : ""}`}>This week: {currentWeekBooked ? "booked" : "not yet booked"}</span></div></div><div className="quick-actions" aria-label="Quick actions"><Link className="quick-action quick-action-fitbot" href="/chat"><img className="quick-action-arc" src="/gitfit-icon.gif" alt="" /><span className="quick-action-content"><span className="quick-action-icon"><IconSparkle /></span><span>Chat with FitBot</span></span><span aria-hidden="true">→</span></Link><Link className="quick-action quick-action-appointments" href="/appointments"><span className="quick-action-content"><span className="quick-action-icon"><IconCalendar /></span><span>View appointments</span></span><span aria-hidden="true">→</span></Link></div><div className="account-sign-out"><form action={signOut}><button className="btn btn-outline" type="submit">Sign out</button></form></div></section>
    <section className="client-dashboard-stats animate-fade-up" style={{ animationDelay: ".1s" }} aria-label="Your weekly stats"><article className="surface-card client-dashboard-stat"><span>Streak</span><strong>{streakWeeks}</strong><small>{streakWeeks === 1 ? "completed week" : "completed weeks"}</small></article><article className="surface-card client-dashboard-stat client-booking-stat"><span>This week</span><strong>{bookedThisWeek} <i>/ {WEEKLY_BOOKING_TARGET}</i></strong><div className="credits-progress" aria-label={`${bookedThisWeek} of ${WEEKLY_BOOKING_TARGET} classes booked`}><span style={{ width: `${weeklyProgressPct}%` }} /></div><small>{bookedThisWeek >= WEEKLY_BOOKING_TARGET ? "Weekly goal reached" : "Classes booked"}</small></article><article className="surface-card client-dashboard-stat"><span>Membership</span><strong>{tierLabel}</strong><small>Current tier</small></article></section>
    {promotions ? <section className="surface-card dashboard-card dashboard-promotions animate-fade-up" style={{ animationDelay: ".14s" }}><div className="dashboard-card-top"><div><h2>Promotions</h2><p className="dashboard-email">Updates and offers from your GitFit team.</p></div></div>{promotions.length ? <div className="promotion-list">{promotions.map((promotion) => <article className="promotion-item" key={promotion.id}><div className="promotion-item-top"><h3>{promotion.subject}</h3><time dateTime={promotion.sent_at ?? undefined}>{formatPromotionDate(promotion.sent_at)}</time></div><p>{previewPromotion(promotion.body)}</p></article>)}</div> : <p className="dashboard-promotions-empty">No promotions right now. Check back soon for updates from the studio.</p>}</section> : null}
    <RecommendedClasses classes={recommendedClasses} reasonLabel={recommendationReason} />
    {goals.length ? <section className="surface-card dashboard-card client-goals-card animate-fade-up" style={{ animationDelay: ".12s" }} aria-labelledby="client-goals-title"><div className="client-section-heading"><div><p className="eyebrow"><span /> Your focus</p><h2 id="client-goals-title">Your goals</h2></div><Link href="/chat">Ask FitBot to update your goals</Link></div><div className="client-goal-list">{goals.map((goal) => <span className="badge badge-brand" key={goal}>{goal}</span>)}</div></section> : null}
    <div className="client-dashboard-grid animate-fade-up" style={{ animationDelay: ".12s" }}><section className="surface-card dashboard-card client-session-card" aria-labelledby="upcoming-bookings-title"><div className="client-section-heading"><div><p className="eyebrow"><span /> On your calendar</p><h2 id="upcoming-bookings-title">Current booked sessions</h2></div><Link href="/appointments">Browse schedule</Link></div><SessionList classes={upcomingBookings} emptyTitle="No upcoming sessions" emptyCopy={<>Browse the <Link href="/appointments">schedule</Link> to book your next class.</>} /></section><section className="surface-card dashboard-card client-session-card" aria-labelledby="recent-sessions-title"><div className="client-section-heading"><div><p className="eyebrow"><span /> Your routine</p><h2 id="recent-sessions-title">Your recent sessions</h2></div><span className="badge badge-neutral">Last {bookingHistory.length}</span></div><SessionList classes={bookingHistory} emptyTitle="No recent sessions yet" emptyCopy="Once you’ve taken a class, your recent booked sessions will appear here." /></section></div>
  </main>;
}
