import { createSupabaseServerClient } from "@/lib/supabase/server";
import type { Intent } from "@/lib/chatbot/types";
import { scoreEntity, scoreTriggerFamily } from "@/lib/chatbot/match-scoring";
const weekdays = ["sunday", "monday", "tuesday", "wednesday", "thursday", "friday", "saturday"]; const instructors = ["sofia", "martinez", "marcus", "lee", "avery", "thompson", "diego", "reyes", "elena", "cruz", "jordan", "blake"];
const hasWord = (message: string, word: string) => new RegExp(`\\b${word}\\b`, "i").test(message); const toDate = (date: Date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`;
const infoPattern = /\b(tell me about|what is|details on|who teaches)\b/i;
function resolveDate(message: string) { const today = new Date(); today.setHours(0, 0, 0, 0); if (hasWord(message, "today") || hasWord(message, "tonight")) return toDate(today); if (hasWord(message, "tomorrow")) { const date = new Date(today); date.setDate(today.getDate() + 1); return toDate(date); } const weekday = weekdays.find((day) => hasWord(message, day)); if (!weekday) return undefined; const date = new Date(today); date.setDate(today.getDate() + ((weekdays.indexOf(weekday) - today.getDay() + 7) % 7)); return toDate(date); }
function resolveTime(message: string) { const match = message.match(/\b(\d{1,2})(?::(\d{2}))?\s*(a\.?(?:m\.?)|p\.?(?:m\.?))\b/i); if (!match) return undefined; let hours = Number(match[1]); if (hours === 12) hours = 0; if (match[3].toLowerCase().startsWith("p")) hours += 12; return `${String(hours).padStart(2, "0")}:${String(Number(match[2] ?? 0)).padStart(2, "0")}`; }
export const classInfoIntent: Intent = { id: "class-info", description: "Provides details for a specific class.", roles: ["client", "staff", "admin"], match: (message) => scoreTriggerFamily(message, [infoPattern]) * (1 + scoreEntity(message, [/\b(yoga|cycling|hiit|boxing|pilates|strength)\b/i])), handle: async (message) => { const normalized = message.toLowerCase(); const type = ["yoga", "cycling", "hiit", "boxing", "pilates", "strength"].find((term) => hasWord(normalized, term)); const date = resolveDate(normalized); const time = resolveTime(normalized); const instructor = instructors.find((term) => hasWord(normalized, term)); const supabase = await createSupabaseServerClient(); let query = supabase.from("classes").select("name, type, instructor, class_date, start_time, capacity, booked_count").order("class_date").order("start_time"); if (type) query = query.ilike("type", type); if (date) query = query.eq("class_date", date); if (time) query = query.eq("start_time", time); if (instructor) query = query.ilike("instructor", `%${instructor}%`); const { data, error } = await query; if (error) return { reply: "I couldn't retrieve class details right now. Please try again shortly." }; const classes = data ?? []; if (!classes.length) return { reply: "I couldn't find a class matching that request." }; if (classes.length > 1) return { reply: `I found a few possible classes. Please be more specific:\n${classes.slice(0, 8).map((row) => `${row.name} — ${row.class_date}, ${row.start_time}`).join("\n")}` }; const row = classes[0]; return { reply: `${row.name} is taught by ${row.instructor} on ${row.class_date} at ${row.start_time}. It has ${row.booked_count} of ${row.capacity} spots booked.`, card: { kind: "schedule", classes: [{ title: row.name, type: row.type, instructor: row.instructor, date: row.class_date, time: row.start_time, capacity: row.capacity, bookedCount: row.booked_count }] } }; } };
